# Generated by Django 2.1.2 on 2018-11-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
                ('c_description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'case',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engr_name', models.CharField(max_length=30)),
                ('engr_email', models.EmailField(max_length=30)),
                ('region', models.CharField(choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('US', 'US')], default='APAC', max_length=4)),
                ('title', models.CharField(choices=[('SE', 'Support Engineer'), ('SEE', 'Support Escalation Engineer'), ('EE', 'Escalation Engineer')], default='SE', max_length=4)),
                ('vote', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'engineer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30)),
                ('queue', models.CharField(blank=True, max_length=30)),
                ('p_description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('ta_name', models.CharField(blank=True, max_length=30)),
                ('t_description', models.TextField(blank=True, max_length=200)),
                ('dispatcher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='office.Engineer')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prod_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='office.Team'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='engr_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Team'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='skill',
            field=models.ManyToManyField(blank=True, max_length=20, to='office.Product'),
        ),
    ]
