# Generated by Django 2.1.2 on 2018-11-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='dispatcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Engineer'),
        ),
    ]
