# Generated by Django 2.1.2 on 2018-11-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20181106_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, choices=[('OPG', 'OPG'), ('WDG', 'WDG'), ('C+E', 'C+E')], max_length=8),
        ),
    ]
