# Generated by Django 2.1.2 on 2018-11-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_team_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proposer', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='engineer',
            name='title',
            field=models.CharField(choices=[('SE', 'Support Engineer'), ('SEE', 'Support Escalation Engineer'), ('EE', 'Escalation Engineer'), ('TA', 'Technical Advisor'), ('TM', 'Team Manager')], default='SE', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='queue',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
