# Generated by Django 2.1.2 on 2018-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_auto_20181107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='queue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
